
ignored = [
"github.com/Masterminds/semver/v3",
"github.com/Masterminds/sprig/v3",
"github.com/pierrec/lz4/v3",
"github.com/russross/blackfriday/v2",
"github.com/cespare/xxhash/v2",
]

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  version = ">=0.9.0"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  version = "1.3.0"
  name = "github.com/gogo/protobuf"

[[override]]
  version = "1.3.1"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  version = "0.1.1"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
#  version = "0.11.12"
  branch = "helm-3-dep"

[[override]]
  name = "github.com/evanphx/json-patch"
  version = "3.0.0"

[[override]]
  name = "helm.sh/helm/v3"
  version = "3.0.0"
  source = "https://github.com/helm/helm"

[[override]]
  name = "github.com/solo-io/go-utils"
  version = "0.11.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.5.2"

[[constraint]]
  name = "github.com/solo-io/reporting-client"
  version = "0.1.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

# make sure all kubernetes code is the same version.
# when updating, update all in the same time.

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.20.6"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.16.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.2"

[[override]]
  name = "k8s.io/klog"
  revision = "9cbb78b20423182f9e5b2a214dd255f5e117d2d1"
  source = "github.com/stefanprodan/klog"

[[override]]
  name = "k8s.io/utils"
  revision = "6ca3b61696b65b0e81f1a39b4937fc2d2994ed6a"

[[override]]
  name = "github.com/go-openapi/spec"
  version = "0.19.2"

[[constraint]]
  name = "knative.dev/serving"
  version = "v0.8.0"

# added to support knative v0.8.0
[[override]]
  name = "golang.org/x/net"
  revision = "aaf60122140d3fcf75376d319f0554393160eb50"

# added to support knative v0.8.0
[[override]]
  name = "golang.org/x/xerrors"
  revision = "a985d3407aa71f30cf86696ee0a2f409709f22e1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/solo-io/go-list-licenses"
  revision = "171e4740d00f71bdc66de3aea93a1b8606f1c1a0"