accessLogger:
  enabled: false
  image:
    repository: access-logger
    tag: v1.10.0-dev-bohanon
  port: 8083
  replicas: 1
  runAsUser: 10101
  serviceName: AccessLog
  stats:
    enabled: true
discovery:
  deployment:
    enablePodSecurityContext: true
    fsGroup: 10101
    image:
      repository: discovery
      tag: v1.10.0-dev-bohanon
    replicas: 1
    runAsUser: 10101
    stats: {}
  enabled: true
  fdsMode: WHITELIST
  serviceAccount: {}
gateway:
  Service: null
  certGenJob:
    cron:
      enabled: false
      schedule: '* * * * *'
    enabled: true
    image:
      repository: certgen
      tag: v1.10.0-dev-bohanon
    restartPolicy: OnFailure
    runAsUser: 10101
    runOnUpdate: false
    setTtlAfterFinished: true
    ttlSecondsAfterFinished: 60
  deployment:
    image:
      repository: gateway
      tag: v1.10.0-dev-bohanon
    replicas: 1
    runAsUser: 10101
  enabled: true
  proxyServiceAccount: {}
  readGatewaysFromAllNamespaces: false
  serviceAccount: {}
  validation:
    allowWarnings: true
    alwaysAcceptResources: true
    disableTransformationValidation: false
    enabled: true
    failurePolicy: Ignore
    secretName: gateway-validation-certs
    validationServerGrpcMaxSizeBytes: 4000000
    warnRouteShortCircuiting: false
    webhook:
      disableHelmHook: false
      enabled: true
gatewayProxies:
  gatewayProxy:
    configMap: {}
    envoyApiVersion: V3
    failover:
      enabled: false
      port: 15443
      secretName: failover-downstream
    gatewaySettings:
      enabled: true
      useProxyProto: false
    globalDownstreamMaxConnections: 250000
    healthyPanicThreshold: 50
    kind:
      deployment:
        replicas: 1
    loopBackAddress: 127.0.0.1
    podTemplate:
      customReadinessProbe: {}
      disableNetBind: true
      enablePodSecurityContext: true
      fsGroup: 10101
      gracefulShutdown:
        enabled: false
        sleepTimeSeconds: 25
      httpPort: 8080
      httpsPort: 8443
      image:
        repository: gloo-envoy-wrapper
        tag: v1.10.0-dev-bohanon
      probes: false
      runAsUser: 10101
      runUnprivileged: true
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
global:
  extauthCustomYaml: true
  glooMtls:
    enabled: false
    envoy:
      image:
        repository: gloo-envoy-wrapper
        tag: v1.10.0-dev-bohanon
    sds:
      image:
        repository: sds
        tag: v1.10.0-dev-bohanon
  glooRbac:
    create: true
    namespaced: false
  glooStats:
    enableStatsRoute: false
    enabled: true
    routePrefixRewrite: /stats/prometheus
    setDatadogAnnotations: false
    statsPrefixRewrite: /stats
  image:
    extended: false
    pullPolicy: IfNotPresent
    registry: quay.io/solo-io
  istioIntegration:
    disableAutoinjection: false
    labelInstallNamespace: false
    whitelistDiscovery: false
  istioSDS:
    enabled: false
gloo:
  deployment:
    image:
      repository: gloo
      tag: v1.10.0-dev-bohanon
    replicas: 1
    restXdsPort: 9976
    runAsUser: 10101
    validationPort: 9988
    xdsPort: 9977
  serviceAccount: {}
ingress:
  deployment:
    image:
      repository: ingress
      tag: v1.10.0-dev-bohanon
    replicas: 1
    runAsUser: 10101
  enabled: false
ingressProxy:
  configMap: {}
  deployment:
    httpPort: 8080
    httpsPort: 8443
    image:
      repository: gloo-envoy-wrapper
      tag: v1.10.0-dev-bohanon
    replicas: 1
  label: ingress-proxy
  loopBackAddress: 127.0.0.1
  service:
    httpPort: 80
    httpsPort: 443
    type: LoadBalancer
k8s:
  clusterName: cluster.local
namespace:
  create: false
settings:
  aws: {}
  create: true
  disableKubernetesDestinations: false
  disableProxyGarbageCollection: false
  enableRestEds: false
  integrations:
    knative:
      enabled: false
      proxy:
        httpPort: 8080
        httpsPort: 8443
        image:
          repository: gloo-envoy-wrapper
          tag: v1.10.0-dev-bohanon
        loopBackAddress: 127.0.0.1
        replicas: 1
        service:
          httpPort: 80
          httpsPort: 443
          type: LoadBalancer
      version: 0.10.0
  invalidConfigPolicy:
    invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
      should run `glooctl check` to find and fix config errors.
    invalidRouteResponseCode: 404
    replaceInvalidRoutes: false
  linkerd: false
